<a href="https://colab.research.google.com/github/Sujan0310/AML-lab/blob/main/Lab1(AML)04_8_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

a=np.array({10,20,30,40})
print(a)

# Corrected the np.arange call.
# The original call had too many arguments, leading to '67' being interpreted as dtype.
# Also, the step was too large for the given range.
b=np.arange(1,11,1) # Example: generates numbers from 1 to 10 with a step of 1
print(b)

c=np.linspace(0,1,5)
print(c)



{40, 10, 20, 30}
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]


In [12]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)
print (A-B)
print(A*B)
print(A/B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
##weather data od manipal of udupi of past 1 month and then find the hottest day and the coldest day




In [25]:
import numpy as np

csv_data = """Date,Max_Temp_C,Min_Temp_C,Humidity_Pct,Rainfall_mm,Remarks
2026-07-01,27.1,23.6,94,18.5,Heavy overcast skies
2026-07-02,27.2,23.5,93,22.0,Continuous monsoon downpour
2026-07-03,27.0,23.7,91,14.2,Scattered heavy showers
2026-07-04,27.1,23.6,93,20.8,"Overcast, consistent rain"
2026-07-05,27.3,23.4,92,11.5,Warmest day of the early month
2026-07-06,26.9,23.5,96,38.5,"High wind gusts, sudden downpour"
2026-07-07,26.8,23.6,92,27.0,Heavy localized rain
2026-07-08,26.4,23.2,94,31.2,"Extreme rain (Precautionary student holiday)"
2026-07-09,26.6,23.5,95,25.1,"Overcast, persistent evening drizzle"
2026-07-10,26.7,23.4,93,19.8,Intermittent monsoon showers
2026-07-11,26.5,23.5,94,29.0,Wet and windy coastal gusts
2026-07-12,26.7,23.6,91,22.4,Short breaks of cloud clearance
2026-07-13,26.8,23.5,92,16.5,Moderate showers
2026-07-14,26.6,23.4,95,32.0,Intense thunderstorm activity
2026-07-15,26.7,23.5,93,24.5,Standard monsoon pattern
2026-07-16,26.8,23.4,91,18.0,Breezy with localized wet spells
2026-07-17,26.5,23.3,94,28.2,"Heavy cloud blanket, low visibility"
2026-07-18,26.6,23.5,92,15.0,Steady rain
2026-07-19,26.7,23.6,90,11.2,Light to moderate drizzle
2026-07-20,26.9,23.5,93,22.8,Rain picking up toward late night
2026-07-21,27.0,23.4,89,9.5,Highest sun availability (~6 hours)
2026-07-22,26.6,23.3,94,34.0,Resurgence of heavy monsoon winds
2026-07-23,26.4,23.1,96,41.5,Severe rainfall warning issued
2026-07-24,26.2,23.2,97,48.0,Flooding in low-lying coastal zones
2026-07-25,26.1,23.3,96,52.0,"Maximum precipitation (School holiday declared)"
2026-07-26,26.5,23.4,94,26.5,Heavy downpours continuing
2026-07-27,26.7,23.5,93,19.0,"Gentle coastal winds, heavy rain"
2026-07-28,26.8,23.4,95,21.4,Steady rainfall
2026-07-29,26.8,23.2,94,14.8,Coldest day drop to 23.2C
2026-07-30,27.0,23.6,92,11.0,Light morning rain
2026-07-31,27.1,23.8,91,9.2,Breaks in cloud cover
2026-08-01,27.5,24.2,93,13.0,"Humid afternoons, occasional heavy rain"
2026-08-02,27.8,24.5,92,10.5,"Mild morning mist, scattered drizzle"
2026-08-03,27.6,24.4,94,24.0,Light rain mixed with morning fog
2026-08-04,28.3,24.4,91,18.0,Periods of continuous monsoon rain
"""

# Splitting lines and removing header
lines = csv_data.strip().split('\n')[1:]

# Manual parsing to handle quoted commas correctly
parsed_data = []
for line in lines:
    if '"' in line:
        # Split by quotes to protect the internal comma
        parts = line.split('"')
        first_part = parts[0].strip(',').split(',')
        remark = parts[1]
        parsed_data.append(first_part + [remark])
    else:
        parsed_data.append(line.split(','))

# Creating NumPy arrays
data_array = np.array(parsed_data)
dates = data_array[:, 0]
max_temps = data_array[:, 1].astype(float)
min_temps = data_array[:, 2].astype(float)

# NumPy statistical analysis
hottest_idx = np.argmax(max_temps)
coldest_idx = np.argmin(min_temps)
overall_avg = np.mean(np.concatenate([max_temps, min_temps]))

print("\n--- Analysis Results (Strictly NumPy) ---")
print(f"Hottest Day: {dates[hottest_idx]} with Max Temperature of {max_temps[hottest_idx]}°C")
print(f"Coldest Day: {dates[coldest_idx]} with Min Temperature of {min_temps[coldest_idx]}°C")
print(f"Overall Average Temperature: {overall_avg:.2f}°C")


--- Analysis Results (Strictly NumPy) ---
Hottest Day: 2026-08-04 with Max Temperature of 28.3°C
Coldest Day: 2026-07-23 with Min Temperature of 23.1°C
Overall Average Temperature: 25.21°C


In [26]:
import pandas as pd

student = {
    "Name": ["A", "B", "C", "D"],
    "Age": [21, 22, 23, 22],
    "Marks": [78, 65, 90, 85]
}

df = pd.DataFrame(student)
print(df)

  Name  Age  Marks
0    A   21     78
1    B   22     65
2    C   23     90
3    D   22     85


In [27]:
from sklearn.datasets import load_iris

iris_data = load_iris(as_frame=True)
d = iris_data.frame

print(d.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


In [31]:
df.info()

print(df.describe())

print(df.shape)

print(df.columns.tolist())


print(df.tail())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   Marks   4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
             Age      Marks
count   4.000000   4.000000
mean   22.000000  79.500000
std     0.816497  10.847427
min    21.000000  65.000000
25%    21.750000  74.750000
50%    22.000000  81.500000
75%    22.250000  86.250000
max    23.000000  90.000000
(4, 3)
['Name', 'Age', 'Marks']
  Name  Age  Marks
0    A   21     78
1    B   22     65
2    C   23     90
3    D   22     85


In [33]:
print(d[['sepal length (cm)', 'target']].head())


print(d.iloc[:5])

print(d.loc[[10, 20]])

   sepal length (cm)  target
0                5.1       0
1                4.9       0
2                4.7       0
3                4.6       0
4                5.0       0
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
10                5.4               3.7                1.5               0.2   
20                5.4               3.4                1.7               0.2   

    target  
10       0  
20       0  

In [37]:
d[d['target'] == 1]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
50,7.0,3.2,4.7,1.4,1
51,6.4,3.2,4.5,1.5,1
52,6.9,3.1,4.9,1.5,1
53,5.5,2.3,4.0,1.3,1
54,6.5,2.8,4.6,1.5,1
55,5.7,2.8,4.5,1.3,1
56,6.3,3.3,4.7,1.6,1
57,4.9,2.4,3.3,1.0,1
58,6.6,2.9,4.6,1.3,1
59,5.2,2.7,3.9,1.4,1


In [ ]:
d.sort_values(by='sepal length (cm)')